name: Cross Compile Go Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64] # 根据需要选择架构，例如arm64, 386等
        exclude:
          - goos: darwin
            goarch: arm64 # macOS不支持arm64的交叉编译，除非你有M1芯片的Mac进行本地编译

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        GOOS=${{ env.GOOS }} GOARCH=${{ env.GOARCH }} go build -v -o bin/${{ matrix.goos }}-${{ matrix.goarch }}/tcping ./cmd/tcping/main.go

    - name: Upload binaries
      if: success() # 只在构建成功时上传
      uses: actions/upload-artifact@v2
      with:
        name: tcping-${{ matrix.goos }}-${{ matrix.goarch }}
        path: bin/${{ matrix.goos }}-${{ matrix.goarch }}/tcping
